In [1]:
import numpy as np

In [3]:
## Array (Create a single dimensional array)
a_1 = np.array([1,2,3,4,5])
print(a_1)

[1 2 3 4 5]


In [4]:
type(a_1)

numpy.ndarray

In [5]:
a_2 = np.array([(1,2,3),(3,5,6)])
a_2

array([[1, 2, 3],
       [3, 5, 6]])

### Numpy Operations

In [6]:
a_2

array([[1, 2, 3],
       [3, 5, 6]])

In [7]:
a_2.ndim

2

In [9]:
a_2.itemsize

4

In [10]:
a_2.dtype

dtype('int32')

In [11]:
a_2 = np.array([(1.6,2.6,3.4),(3.5,5.6,6)])
a_2

array([[1.6, 2.6, 3.4],
       [3.5, 5.6, 6. ]])

In [12]:
a_2.dtype

dtype('float64')

In [13]:
a_2.shape

(2, 3)

In [16]:
a_2.reshape(3,2)

array([[1.6, 2.6],
       [3.4, 3.5],
       [5.6, 6. ]])

In [17]:
a_2.reshape(1,6)

array([[1.6, 2.6, 3.4, 3.5, 5.6, 6. ]])

### Picking an element from array

In [19]:
a_2 = np.array([(1.6,2.6,3.4),(3.5,5.6,6),((30.5,05.60,6))])
a_2

array([[ 1.6,  2.6,  3.4],
       [ 3.5,  5.6,  6. ],
       [30.5,  5.6,  6. ]])

In [20]:
a_2[1]

array([3.5, 5.6, 6. ])

In [21]:
a_2[1,1]

5.6

In [22]:
a_2[1,2]

6.0

In [23]:
a_2[0:2]

array([[1.6, 2.6, 3.4],
       [3.5, 5.6, 6. ]])

In [24]:
a_2[0:2,2]

array([3.4, 6. ])

In [25]:
# generate  some numbers b/w a range of equal diff
a = np.linspace(1,100,10)
a

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [26]:
# generate  some numbers b/w a range of equal diff
a = np.linspace(10,100,10)
a

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
a.min()

10.0

In [28]:
a.max()

100.0

In [29]:
a.mean()

55.0

In [30]:
a.sum()

550.0

In [31]:
a.argmax()

9

In [32]:
a_2 = np.array([(1.6,2.6,3.4),(3.5,5.6,6),((30.5,05.60,6))])
a_2

array([[ 1.6,  2.6,  3.4],
       [ 3.5,  5.6,  6. ],
       [30.5,  5.6,  6. ]])

In [33]:
a_2.argmax()

6

In [34]:
a_2.max()

30.5

In [35]:
a_2.argmin()

0

In [40]:
a_2

array([[ 1.6,  2.6,  3.4],
       [ 3.5,  5.6,  6. ],
       [30.5,  5.6,  6. ]])

In [38]:
a_2.sum(axis=0) #column size

array([35.6, 13.8, 15.4])

In [39]:
a_2.sum(axis=1) #row wise

array([ 7.6, 15.1, 42.1])

In [41]:
np.sqrt(a_2)

array([[1.26491106, 1.61245155, 1.84390889],
       [1.87082869, 2.36643191, 2.44948974],
       [5.52268051, 2.36643191, 2.44948974]])

In [45]:
i = np.array([(1,2,3),(4,5,6)])
j = np.array([(10,20,30),(40,50,60)])

In [46]:
i

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
j

array([[10, 20, 30],
       [40, 50, 60]])

In [48]:
i+j

array([[11, 22, 33],
       [44, 55, 66]])

In [49]:
i-j

array([[ -9, -18, -27],
       [-36, -45, -54]])

In [50]:
i*j

array([[ 10,  40,  90],
       [160, 250, 360]])

In [51]:
i/j

array([[0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1]])

#### concatination of arrays

In [52]:
i = np.array([(1,2,3),(4,5,6)])
j = np.array([(10,20,30),(40,50,60)])

In [57]:
## vertical stacking
k = np.vstack((i,j))

In [58]:
k

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30],
       [40, 50, 60]])

In [59]:
## horizontal stacking
k = np.hstack((i,j))

In [60]:
k

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [63]:
## arange function
np.arange(10,100,5.5)

array([10. , 15.5, 21. , 26.5, 32. , 37.5, 43. , 48.5, 54. , 59.5, 65. ,
       70.5, 76. , 81.5, 87. , 92.5, 98. ])

In [64]:
np.arange(10,100,7.2)

array([10. , 17.2, 24.4, 31.6, 38.8, 46. , 53.2, 60.4, 67.6, 74.8, 82. ,
       89.2, 96.4])

In [65]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [67]:
np.ones((5,5,))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
np.ones((5,5,))+20

array([[21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.]])

In [69]:
np.ones((5,5,))*20

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [74]:
np.random.randint(0,100)

95

In [79]:
np.random.randint(0,100,5)

array([80, 86, 41,  2,  8])

In [95]:
np.random.seed(1)
np.random.randint(0,100,(5,5))

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87]])